export const Plans = [
  {
    id: "trial",
    name: "Freemium",
    description: "Try SewDesk free for 14 days.",
    price: 0,
    period: "14 days",
    cta: "Start Free Trial",
    highlight: false,
    features: [
      "Unlimited customers",
      "Unlimited orders",
      "Customer measurements",
      "Bookings",
      "Invoices",
      "Payment tracking",
      "Expense tracking",
      "Inventory management",
      "Basic reports",
      "Basic analytics",
    ],
  },
  {
    id: "sewdesk",
    name: "SewDesk",
    description: "Everything you need to run your tailoring business.",
    price: 5000,
    period: "month",
    cta: "Choose SewDesk",
    highlight: true,
    badge: "Most Popular",
    features: [
      "Unlimited customers",
      "Unlimited orders",
      "Customer measurements",
      "Unlimited bookings",
      "Invoices",
      "Payment tracking",
      "Expense tracking",
      "Inventory management",
      "Advanced reports",
      "Business branding",
      "Staff management",
      "Automated reminders",
      "Customer management",
    ],
  },
  {
    id: "sewdesk_pro",
    name: "SewDesk Pro",
    description: "Advanced tools for growing tailoring businesses.",
    price: 7000,
    period: "month",
    cta: "Choose SewDesk Pro",
    highlight: false,
    features: [
      "Everything in SewDesk",
      "Advanced analytics",
      "Advanced inventory management",
      "Multiple staff accounts",
      "Staff roles and permissions",
      "Multiple branches",
      "Advanced customer automation",
      "Advanced reminders",
      "Profit analytics",
      "Business performance reports",
      "Data export",
      "API integrations",
      "Priority support",
    ],
  },
];
