export const orderData = [
  {
    orderId: "ORD-0001",
    customer: "David Okafor",
    garmentStyle: "Two-piece Senator Outfit",
    status: "Completed",
    amountDue: 0,
    date: "2026-09-05",
  },
  {
    orderId: "ORD-0002",
    customer: "Amaka Eze",
    garmentStyle: "Native Two-Piece",
    status: "In Progress",
    amountDue: 60000,
    date: "2026-09-22",
  },
  {
    orderId: "ORD-0003",
    customer: "Emeka Nwosu",
    garmentStyle: "Simple Kaftan",
    status: "Pending",
    amountDue: 35000,
    date: "2026-09-25",
  },
  {
    orderId: "ORD-0004",
    customer: "Blessing Williams",
    garmentStyle: "Three-Piece Suit",
    status: "Ready",
    amountDue: 0,
    date: "2026-09-20",
  },
  {
    orderId: "ORD-0005",
    customer: "Daniel Adeyemi",
    garmentStyle: "Corporate Shirt & Trouser",
    status: "In Progress",
    amountDue: 45000,
    date: "2026-09-28",
  },
  {
    orderId: "ORD-0006",
    customer: "David Okafor",
    garmentStyle: "Casual Senator Outfit",
    status: "Completed",
    amountDue: 0,
    date: "2026-09-12",
  },
  {
    orderId: "ORD-0007",
    customer: "Samuel Obi",
    garmentStyle: "Aso-Ebi Outfit",
    status: "Cancelled",
    amountDue: 90000,
    date: "2026-09-18",
  },
  {
    orderId: "ORD-0008",
    customer: "Esther Okoro",
    garmentStyle: "Traditional Wedding Outfit",
    status: "Completed",
    amountDue: 0,
    date: "2026-09-16",
  },
];